from typing import Any

class Sound:
    def __init__(self, path: str) -> None: ...

class TextGrid: ...
class FormantUnit: ...

def read(path: str) -> TextGrid: ...

class _PraatModule:
    def call(self, *args: Any) -> Any: ...

praat: _PraatModule

class Formant: ...
class Pitch: ...
